version: '2.2'
options:
  gen-prefix-def: true
  gen-default-stream-def: true
metadata:
  $include:
    - stdint.yaml
    - stdfloat.yaml
    - stdmisc.yaml
    - lttng-ust-log-levels.yaml
  type-aliases:
    clock-int:
      $inherit: uint64
      property-mappings:
        - type: clock
          name: default
          property: value
  clocks:
    default:
      freq: 1000000000
      offset:
        seconds: 1434072888
      $return-ctype: uint64_t
  trace:
    $include: trace-basic.yaml
    byte-order: le
  streams:
    default:
      $default: true
      packet-context-type:
        class: struct
        fields:
          timestamp_begin: clock-int
          timestamp_end: clock-int
          packet_size: uint32
          content_size: uint32
          events_discarded: uint32
      event-header-type:
        class: struct
        fields:
          timestamp: clock-int
          id: uint16
      events:
        tcl_tcl_cmdtrace:
          payload-type:
            class: struct
            fields:
              level: int32 
              cmd:
                class: string

